script: bash ./deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: 189e52c2c347
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
# safelist
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv -in deploy_key.enc -out deploy_key -d
