FROM amazonlinux:2.0.20220218.1
LABEL maintainer="m@yefu.org"
RUN yum install -y  gcc openssl-devel bzip2-devel libffi-devel wget tar gzip make zip
RUN pushd /opt && wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz  \ 
    && tar xzf Python-3.9.6.tgz \
    && pushd Python-3.9.6 \
    && ./configure --enable-optimizations && make altinstall && popd && popd
#RUN apk add --no-cache zip zlib-dev jpeg-dev gcc alpine-sdk
COPY package.sh .
CMD ./package.sh