// for substractionUpto20

export const UPDATE_PROBLEM_NUMBER_S20 = "UPDATE_PROBLEM_NUMBER_S20";

export const UPDATE_PROBLEM_DIRECTION_S20 = "UPDATE_PROBLEM_DIRECTION_S20";

export const UPDATE_MINUEND_S20 = "UPDATE_MINUEND_S20";

export const UPDATE_MINUEND_SELECT_ALL_S20 = "UPDATE_MINUEND_SELECT_ALL_S20";

export const UPDATE_MINUEND_0_9_S20 = "UPDATE_MINUEND_0_9_S20";

export const UPDATE_MINUEND_CLEAR_S20 = "UPDATE_MINUEND_CLEAR_S20";

export const UPDATE_SUBTRAHEND_S20 = "UPDATE_SUBTRAHEND_S20";

export const UPDATE_SUBTRAHEND_SELECT_ALL_S20 =
  "UPDATE_SUBTRAHEND_SELECT_ALL_S20";

export const UPDATE_SUBTRAHEND_0_9_S20 = "UPDATE_SUBTRAHEND_0_9_S20";

export const UPDATE_SUBTRAHEND_CLEAR_S20 = "UPDATE_SUBTRAHEND_CLEAR_S20";

// for substractionMNUpto20

export const UPDATE_PROBLEM_NUMBER_SMN20 = "UPDATE_PROBLEM_NUMBER_SMN20";

export const UPDATE_RESTRICTION_SMN20 = "UPDATE_RESTRICTION_SMN20";

// for additionMNUpto20

export const UPDATE_PROBLEM_NUMBER_AMN20 = "UPDATE_PROBLEM_NUMBER_AMN20";

export const UPDATE_RESTRICTION_AMN20 = "UPDATE_RESTRICTION_AMN20";

// for additionUpto20

export const UPDATE_PROBLEM_NUMBER_A20 = "UPDATE_PROBLEM_NUMBER_A20";

export const UPDATE_PROBLEM_DIRECTION_A20 = "UPDATE_PROBLEM_DIRECTION_A20";

export const UPDATE_ADDEND_A20 = "UPDATE_ADDEND_A20";

export const UPDATE_ADDEND_SELECT_ALL_A20 = "UPDATE_ADDEND_SELECT_ALL_A20";

export const UPDATE_ADDEND_0_9_A20 = "UPDATE_ADDEND_0_9_A20";

export const UPDATE_ADDEND_CLEAR_A20 = "UPDATE_ADDEND_CLEAR_A20";

// for GreaterThanLessThan

export const UPDATE_PROBLEM_NUMBER_GL = "UPDATE_PROBLEM_NUMBER_GL";
