# This is a basic workflow to help you get started with Actions

name: Deploy the backend to lambda

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, workflow_dev ]
    paths:
      - backend/**
  pull_request:
    branches: [ master ]
    paths:
      - backend/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build the container that creates the package
      working-directory: backend
      run: docker build . -t tt -f Dockerfile.packager
    - name: package
      working-directory: backend
      run: docker run --rm --user $(id -u):$(id -g) -v ${PWD}:/source tt && ls
    - name: inspect
      run: ls backend
    - uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: blankmath
        zip_file: backend/deploy.zip

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
